// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeUCmyOIJ_8v8GRpGnOGwHLWbHrdKFYZw',
    appId: '1:257619936164:web:af801d2283bfb8fa027731',
    messagingSenderId: '257619936164',
    projectId: 'chat-app-79232',
    authDomain: 'chat-app-79232.firebaseapp.com',
    storageBucket: 'chat-app-79232.firebasestorage.app',
    measurementId: 'G-TYZDZJHSTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4KrU1P8aTsdBmDJoVRSdeGYg3zg8mghM',
    appId: '1:257619936164:android:9396df5518d9b39a027731',
    messagingSenderId: '257619936164',
    projectId: 'chat-app-79232',
    storageBucket: 'chat-app-79232.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu-onM93vKU25_YRKDr1Ehq1GmCv-QLo4',
    appId: '1:257619936164:ios:d2c989a2826293fc027731',
    messagingSenderId: '257619936164',
    projectId: 'chat-app-79232',
    storageBucket: 'chat-app-79232.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu-onM93vKU25_YRKDr1Ehq1GmCv-QLo4',
    appId: '1:257619936164:ios:d2c989a2826293fc027731',
    messagingSenderId: '257619936164',
    projectId: 'chat-app-79232',
    storageBucket: 'chat-app-79232.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeUCmyOIJ_8v8GRpGnOGwHLWbHrdKFYZw',
    appId: '1:257619936164:web:e7c2f4042c079696027731',
    messagingSenderId: '257619936164',
    projectId: 'chat-app-79232',
    authDomain: 'chat-app-79232.firebaseapp.com',
    storageBucket: 'chat-app-79232.firebasestorage.app',
    measurementId: 'G-RKCF9S0JWV',
  );

}